apiVersion: "apps/v1"
kind: Deployment
metadata:
  labels:
    stage: production
    name: prisma
    app: prisma
  namespace: prisma
  name: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      stage: production
      name: prisma
      app: prisma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: prisma
        app: prisma
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: test
          image: debian
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          volumeMounts:
            - name: html
              mountPath: /html
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                date >> /html/index.html;
                sleep 1;
              done
        - name: prisma
          image: prismagraphql/prisma:1.34
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "800m"
              memory: "800Mi"
          ports:
          - containerPort: 4466
            protocol: TCP
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG
