apiVersion: v1
kind: Service
metadata:
  namespace: prisma
  name: mongo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mongo-port
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    component: "db"
  type: NodePort
status:
  loadBalancer: {}