apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  namespace: prisma
  labels:
    name: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mongo
        uri: mongodb://mongo:27017