apiVersion: v1
kind: Service
metadata:
  namespace: prisma
  name: prisma
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: prisma-port
    port: 4466
    protocol: TCP
    targetPort: 4466
  selector:
    stage: production
    name: prisma
    app: prisma
  type: NodePort
status:
  loadBalancer: {}